version: "3.8"
services:
  database:
    build: ./database/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: ./app/
    depends_on:
      database:
        condition: service_healthy
    links:
      - database